# Generated by Django 2.2.3 on 2019-07-10 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_votecount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votecount',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='votecount',
            old_name='user_id',
            new_name='user',
        ),
    ]
